### ISSUE TITLE
Create Flashcards

### ISSUE THREAD

**Issue by ryutaudo** [gerpanese/kovoel#3]
## Description
A page that generates flashcard with voice recognition and stores new flashcard to database

## Subtask
- [x] Create CreateCard Component.
- [x] Create CreateCard Container.
- [x] Add a case for the reducer.
- [x] Add actions to action file.
- [ ] Create a database table for cards
- [ ] Setup router to save card info to the database.
- [ ] Create util function to make a request to the server.
